# Generated by Django 4.2 on 2023-10-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bno', models.IntegerField(primary_key=True, serialize=False)),
                ('rno', models.IntegerField()),
                ('towards', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('rno', models.IntegerField(primary_key=True, serialize=False)),
                ('stpt', models.CharField(max_length=50)),
                ('ept', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Route1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Route10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Route11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Route12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Route13',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Route14',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Route15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Route16',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Route17',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Route18',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Route19',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Route2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Route20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Route21',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Route22',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Route23',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Route24',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Route25',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Route26',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Route27',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Route28',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Route29',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Route3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Route30',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Route4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Route5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Route6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Route7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Route8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Route9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=4)),
            ],
        ),
    ]
