# Generated by Django 4.2 on 2023-10-11 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gchalo', '0003_routedetails_delete_route1_delete_route10_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bus',
        ),
    ]
