# Generated by Django 4.2 on 2023-10-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gchalo', '0004_delete_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bno', models.IntegerField()),
                ('rno', models.IntegerField()),
                ('towards', models.CharField(max_length=20)),
            ],
        ),
    ]
