# Generated by Django 4.2.6 on 2023-10-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gchalo', '0005_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routedetails_shift2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rno', models.IntegerField()),
                ('stop', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=8)),
            ],
        ),
        migrations.RenameModel(
            old_name='Routedetails',
            new_name='Routedetails_shift1',
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
    ]
