# Generated by Django 4.2.6 on 2023-10-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gchalo', '0006_routedetails_shift2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bno', models.IntegerField()),
                ('rno', models.IntegerField()),
                ('towards', models.CharField(max_length=20)),
                ('shift', models.IntegerField()),
            ],
        ),
    ]
