# Generated by Django 4.2.6 on 2023-10-18 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gchalo', '0009_subscribe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
