# Generated by Django 4.2.6 on 2023-10-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gchalo', '0011_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_token', models.CharField(max_length=255)),
            ],
        ),
    ]
