# Generated by Django 4.2.6 on 2023-10-18 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gchalo', '0012_adminverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminVerification',
        ),
    ]
