from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="HomePage"),
    path("displayqr/",views.display_qr,name="DisplayQR"),
    path("loginpage/", views.login_page, name="LoginPage"),
    path("studentsignuppage/", views.student_signup_page, name="StudentSignupPage"),
    path("studentloginpage/", views.student_login_page, name="StudentLoginPage"),
    path("subscribepage/", views.subscribe_page, name="SubscribePage"),
    path("subscribe/", views.subscribe, name="Subscribe"),
    path("unsubscribe/", views.unsubscribe, name="Unsubscribe"),
    path("login/", views.login_user, name="Login"),
    path("studentlogin/", views.student_login, name="StudentLogin"),
    path("logout/", views.logout_user, name="Logout"),
    path("adminsignuppage/", views.admin_signup_page, name="AdminSignupPage"),
    path("adminsignup/", views.admin_signup, name="AdminSignup"),
    path("studentsignup/", views.student_signup, name="StudentSignup"),
    path("addbus/<int:rno>/<int:shift>/", views.add_bus, name="AddBus"),
    path("addroute/",views.add_route,name="AddRoute"),
    path("editroute/",views.edit_route,name="EditRoute"),
    path("bus/",views.bus,name="Bus"),
    path("route/",views.route,name="Route"),
    path("adminpanel/",views.admin_panel,name="AdminPanel"),
    path("editstop/<int:rno>/<int:shift>/",views.edit_stop,name="EditStop"),
    path("editbus/<int:rno>/<int:shift>/",views.edit_bus,name="EditBus"),
    path("modifyroute/",views.modify_route,name="ModifyRoute"),
    path("updatestop/<int:id>/<int:rno>/<int:shift>/",views.update_stop,name="UpdateStop"),
    path("updatebus/<int:id>/<int:rno>/<int:shift>/",views.update_bus,name="UpdateBus"),
    path("updateroute/<int:rno>/",views.update_route,name="UpdateRoute"),
    path("addstop/<int:rno>/<int:shift>/",views.add_stop,name="AddStop"),
    path("displayroute/",views.display_route,name="DisplayRoute"),
    path("displayparticularroute/",views.display_particular_route,name="DisplayParticularRoute"),
    path("searchstop/",views.search_stop,name="SearchStop"),
    path("studentverifyemail/<str:token>/",views.student_verify_email,name="StudentVerify"),
    path("adminverifyemail/<str:token>/",views.admin_verify_email,name="AdminVerify"),
    path("studentforgotpasswordpage/",views.student_forgot_password,name="StudentForgotPasswordPage"),
    path("studentresetpassword/",views.student_reset_password,name="StudentResetPassword"),
    path("studentpasswordreset/<str:usname>/",views.student_password_reset,name="StudentPasswordReset"),
    path("studentpasswordresetpage/<str:token>/",views.student_reset_password_page,name="StudentResetPasswordPage"),
    path("adminforgotpasswordpage/",views.admin_forgot_password,name="AdminForgotPasswordPage"),
    path("adminresetpassword/",views.admin_reset_password,name="AdminResetPassword"),
    path("adminpasswordreset/<str:usname>/",views.admin_password_reset,name="AdminPasswordReset"),
    path("adminpasswordresetpage/<str:token>/",views.admin_reset_password_page,name="AdminResetPasswordPage"),
    path("respondmessage/",views.respond_message,name="RespondMessage"),
    path("portfoliopage/",views.portfolio_page,name="PortfolioPage"),
    path("personalisedroutes/",views.personalize_route,name="PersonaliseRoute")
]